"use client";
// import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { NavigationBar } from "@/components/NavigationBar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <NextUIProvider>
          <NavigationBar />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
